### ISSUE TITLE
public配下をgitの監視対象から除外する

### ISSUE THREAD

**Issue by juuun-jp** [juuun-jp/chuo-university#6]
# 概要
public配下がgitに取り込まれ差分等が見づらいため、gitの監視対象から除外する

**Comment by skmt-shinj007** [comment]
作業完了。

**【PCレイアウト】横並びイメージのコンポーネント追加**
上記のPRがマージされたら、この課題のPRを作る。

動作確認はこっちでもやったけど、PR見て問題なさそうならマージお願い。

**Comment by skmt-shinj007** [comment]
2人で対応済
