### ISSUE TITLE
/photo 写真モーダルの写真サイズ検討

### ISSUE THREAD

**Issue by skmt-shinj007** [juuun-jp/chuo-university#61]
### **概要**
フォトギャラリーの写真を押下後に展開するモーダルで、表示する写真が縦の写真や縦幅が大きい写真の場合切り取られるので、表示方法をどうするか検討する。

**Comment by juuun-jp** [comment]
横も縦も画面におさまるようにそのまま表示すればいいのでは？
逆に切り取らない仕組み。
